//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.26 at 04:05:15 PM IST 
//


package com.ina.parameters.packages.xml.v8.catm712;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PublicRSAKey1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PublicRSAKey1"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Mdlus" type="{urn:iso:std:iso:20022:tech:xsd:catm.007.001.02}Max5000Binary"/&gt;
 *         &lt;element name="Expnt" type="{urn:iso:std:iso:20022:tech:xsd:catm.007.001.02}Max5000Binary"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PublicRSAKey1", propOrder = {
    "mdlus",
    "expnt"
})
public class PublicRSAKey1 {

    @XmlElement(name = "Mdlus", required = true)
    protected byte[] mdlus;
    @XmlElement(name = "Expnt", required = true)
    protected byte[] expnt;

    /**
     * Gets the value of the mdlus property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getMdlus() {
        return mdlus;
    }

    /**
     * Sets the value of the mdlus property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setMdlus(byte[] value) {
        this.mdlus = value;
    }

    /**
     * Gets the value of the expnt property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getExpnt() {
        return expnt;
    }

    /**
     * Sets the value of the expnt property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setExpnt(byte[] value) {
        this.expnt = value;
    }

}
