//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.26 at 04:05:14 PM IST 
//


package com.ina.parameters.packages.xml.v8.catm118;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PartyType5Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="PartyType5Code"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="OPOI"/&gt;
 *     &lt;enumeration value="OriginatingPOI"/&gt;
 *     &lt;enumeration value="ACCP"/&gt;
 *     &lt;enumeration value="MERC"/&gt;
 *     &lt;enumeration value="ACQR"/&gt;
 *     &lt;enumeration value="ITAG"/&gt;
 *     &lt;enumeration value="MTMG"/&gt;
 *     &lt;enumeration value="MasterTerminalManager"/&gt;
 *     &lt;enumeration value="TMGT"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "PartyType5Code")
@XmlEnum
public enum PartyType5Code {

    OPOI("OPOI"),
    @XmlEnumValue("OriginatingPOI")
    ORIGINATING_POI("OriginatingPOI"),
    ACCP("ACCP"),
    MERC("MERC"),
    ACQR("ACQR"),
    ITAG("ITAG"),
    MTMG("MTMG"),
    @XmlEnumValue("MasterTerminalManager")
    MASTER_TERMINAL_MANAGER("MasterTerminalManager"),
    TMGT("TMGT");
    private final String value;

    PartyType5Code(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PartyType5Code fromValue(String v) {
        for (PartyType5Code c: PartyType5Code.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
