//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.26 at 04:05:14 PM IST 
//


package com.ina.parameters.packages.xml.v8.catm118;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for POIComponentType5Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="POIComponentType5Code"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="AQPP"/&gt;
 *     &lt;enumeration value="APPR"/&gt;
 *     &lt;enumeration value="TLPR"/&gt;
 *     &lt;enumeration value="SCPR"/&gt;
 *     &lt;enumeration value="SERV"/&gt;
 *     &lt;enumeration value="TERM"/&gt;
 *     &lt;enumeration value="DVCE"/&gt;
 *     &lt;enumeration value="SECM"/&gt;
 *     &lt;enumeration value="APLI"/&gt;
 *     &lt;enumeration value="EMVK"/&gt;
 *     &lt;enumeration value="EMVO"/&gt;
 *     &lt;enumeration value="MDWR"/&gt;
 *     &lt;enumeration value="DRVR"/&gt;
 *     &lt;enumeration value="OPST"/&gt;
 *     &lt;enumeration value="MRPR"/&gt;
 *     &lt;enumeration value="CRTF"/&gt;
 *     &lt;enumeration value="TMSP"/&gt;
 *     &lt;enumeration value="SACP"/&gt;
 *     &lt;enumeration value="SAPR"/&gt;
 *     &lt;enumeration value="SecurityParameters"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "POIComponentType5Code")
@XmlEnum
public enum POIComponentType5Code {

    AQPP("AQPP"),
    APPR("APPR"),
    TLPR("TLPR"),
    SCPR("SCPR"),
    SERV("SERV"),
    TERM("TERM"),
    DVCE("DVCE"),
    SECM("SECM"),
    APLI("APLI"),
    EMVK("EMVK"),
    EMVO("EMVO"),
    MDWR("MDWR"),
    DRVR("DRVR"),
    OPST("OPST"),
    MRPR("MRPR"),
    CRTF("CRTF"),
    TMSP("TMSP"),
    SACP("SACP"),
    SAPR("SAPR"),
    @XmlEnumValue("SecurityParameters")
    SECURITY_PARAMETERS("SecurityParameters");
    private final String value;

    POIComponentType5Code(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static POIComponentType5Code fromValue(String v) {
        for (POIComponentType5Code c: POIComponentType5Code.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
