spring:
  application:
    name: ina-pay-tms
  jpa:
    generate-ddl: true
    ddl-auto: create
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: geidea_tms_db

server:
  port: 8082
  error:
    path: /error


ina:
  database:
    url: jdbc:postgresql://10.69.24.176:5438/geidea_tms_db
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
    poolName: INAMHHikariCP
    maxPoolSize: 300
    minimumIdle: 10
    idleTimeout: 600000
    maxLifetime: 1800000
    connectionTimeout: 60000
    leakDetectionThreshold: 100000
    autoCommit: false
    cachePrepStmts: true
    prepStmtCacheSize: 1024
    prepStmtCacheSqlLimit: 4096
    useServerPrepStmts: true
    housekeepingPeriodMs: 60000

  property-config:
    issuerDetails:
      "RBL": "123456789012345"
      "MADA": "678901234567890"
      "ANM": "234567890123456"
      "TXN": "789012345678901"
      "TMS": "890123456789012"
    keyType:
      "ECC" : "ECDH,ECMQV,ECDSA,EdDSA,ECIES,Curve25519,Curve448,secp256k1,SM2"
      "RSA" : "RSASSA-PKCS1-v1_5,RSASSA-PSS,RSAES-PKCS1-v1_5,RSAES-OAEP,RSA-SHA256, RSA-SHA512,TLS/SSL, IPsec, SSH,PKI, S/MIME, CMS"
    certificateSubRequest:
      "org": "INA_PAYMENTS"
      "locale": "BANGALORE"
      "state": "KA"
      "country": "IN"
    algoToBeUsed:
      "CA" : "ECP521"
      "LEAF": "ECP256"
    certTypeAndAssociatedParent:
      "TXN_SUB_CA" : "TXN_SUB_CA,ROOT_CA"
      "TXN_SERVER_SUB_CA" : "TXN_SERVER_SUB_CA,TXN_SUB_CA,ROOT_CA"
      "TXN_SPOS_SUB_CA" : "TXN_SPOS_SUB_CA,TXN_SUB_CA,ROOT_CA"
      "TXN_SERVER_ENCRYPTION_KP": "TXN_SERVER_ENCRYPTION_KP,TXN_SERVER_SUB_CA,TXN_SUB_CA,ROOT_CA"
      "TXN_SERVER_SIGNATURE_KP": "TXN_SERVER_SIGNATURE_KP,TXN_SERVER_SUB_CA,TXN_SUB_CA,ROOT_CA"
      "TXN_SPOS_ENCRYPTION_KP": "TXN_SPOS_ENCRYPTION_KP,TXN_SPOS_SUB_CA,TXN_SUB_CA,ROOT_CA"
      "TXN_SPOS_SIGNATURE_KP": "TXN_SPOS_SIGNATURE_KP,TXN_SPOS_SUB_CA,TXN_SUB_CA,ROOT_CA"
    dekKeyConfiguration:
      "KEY_TYPE" : "DEK"
      "USE_MODE" : "BOTH"
      "ALGO" : "A128"
      "AEK_KEY_SIZE": "16"
    ivForAEKEncryptionAndDecryption: "98790829879082765109538765109538"
    keyExpiryInMilliSeconds: "31536000000"
    tr31KeyBlockHeader:
      "keyBlockType": "D"
      "keyUsage": "S2"
      "export": "E"
      "algorithm": "E"
      "keyUseFor": "B"
      "version": "00"
    pkiConfig:
      baseUrl: "http://10.69.0.36:8000"
      pathToGenerateCert: "/v1/serv/init"
      pathToSignCert: "/v1/serv/cert"
    cryptoConfig:
      baseUrl: "http://10.69.0.36:8001"
      hsmName: "PS"
      pathToGenerateDEK: "/v1/crypto/key_gen"
      pathToGenerateRandomNumber: "/v1/crypto/rand_gen"
      pathToGenerateEncryptedAEK: "/v1/crypto/data_encr"
      pathToDecryptAEK: "/v1/crypto/data_decr"
      pathToGenerateKeyPair: "/v1/crypto/kp_gen"
      pathToGenSign: "/v1/crypto/gen_sign"
  http:
    max-total: 1000
    max-route: 1000
    conn-timeout: 300000
    read-timeout: 100000
timestamp:
  validity:
    ms: 2800000



client:
  reference: anm-client
keycloak:
  auth:
    issuer: http://10.69.0.36:8080/realms/GeIdea
  certs:
    url: http://10.69.0.36:8080/realms/GeIdea/protocol/openid-connect/certs

application:
  roles: '[
    {"role": "SPOS_USER", "endpoints": [
    "/tms/api/v1/release/create",
    "/tms/api/v1/parameters/getParameters",
    "/tms/api/v1/parameters/getParamChecksum",
    "/tms/api/v1/device/updateDeviceRevokeStatus",
    "/tms/api/v1/device/unblock",
    "/tms/api/v1/device/block",
    "/tms/api/v1/device/setup/tmsInit",
    "/tms/api/v1/device/certs/viewCertInfo",
    "/tms/api/v1/device/certs/getServerCertsWithStatus",
    "/tms/api/v1/device/certs/getAllServerCerts",
    "/tms/api/v1/device/certs/getAllDeviceCerts",
    "/tms/api/v1/device/certs/generateServerL4Certs",
    "/tms/api/v1/device/certs/generateServerCerts",
    "/tms/api/v1/device/certs/generateRootCert",
    "/key/api/v1/rotateDEKAndAEKKey",
    "/key/api/v1/getAllAEKAndDEKServerKeys",
    "/key/api/v1/generateAEKKey",
    "/key/api/v1/getAllSPOSKeys",
    "/key/api/v1/generateSPOSAuthKey",
    "/api/v1/ping",
    "/api/v1/health",
    "/api/v1/error"
    ]},
    {"role": "BIZOPS", 
    "endpoints": [
    "/tms/api/v1/device/unblock",
    "/tms/api/v1/device/block"
    ]},
    {
    "role": "CHECKER", 
    "endpoints": 
    [  "/tms/api/v1/device/certs/viewCertInfo",
       "/tms/api/v1/device/certs/getServerCertsWithStatus",
       "/tms/api/v1/device/certs/getAllServerCerts",
       "/tms/api/v1/device/certs/getAllDeviceCerts",
       "/tms/api/v1/device/certs/generateServerL4Certs",
       "/tms/api/v1/device/certs/generateServerCerts",
       "/tms/api/v1/device/certs/generateRootCert"
    ]},
    {
    "role": "KEY_CUSTODIAN_CHECKER", 
    "endpoints": 
    [ "/key/api/v1/rotateDEKAndAEKKey",
      "/key/api/v1/getAllAEKAndDEKServerKeys",
      "/key/api/v1/generateAEKKey",
      "/key/api/v1/getAllSPOSKeys",
      "/key/api/v1/generateSPOSAuthKey"
    ]},
    {"role": "ADMIN", "endpoints": [
    "/tms/api/v1/release/create",
    "/tms/api/v1/parameters/getParameters",
    "/tms/api/v1/parameters/getParamChecksum",
    "/tms/api/v1/device/updateDeviceRevokeStatus",
    "/tms/api/v1/device/unblock",
    "/tms/api/v1/device/block",
    "/tms/api/v1/device/setup/tmsInit",
    "/tms/api/v1/device/certs/viewCertInfo",
    "/tms/api/v1/device/certs/getServerCertsWithStatus",
    "/tms/api/v1/device/certs/getAllServerCerts",
    "/tms/api/v1/device/certs/getAllDeviceCerts",
    "/tms/api/v1/device/certs/generateServerL4Certs",
    "/tms/api/v1/device/certs/generateServerCerts",
    "/tms/api/v1/device/certs/generateRootCert",
    "/key/api/v1/rotateDEKAndAEKKey",
    "/key/api/v1/getAllAEKAndDEKServerKeys",
    "/key/api/v1/generateAEKKey",
    "/key/api/v1/getAllSPOSKeys",
    "/key/api/v1/generateSPOSAuthKey",
    "/api/v1/ping",
    "/api/v1/health",
    "/api/v1/error"
    ]}
    ]'


tms:
  request:
    krdSign2: "test.model"
    model: "P01"
    make: "Geidea"
    shortName: "GeideaUAT01"
    trsMIdCounter: "000001"
    appVersion: "V10.0"
    tid : "6383593278311080"
    trsmId : "63835932"
    serialNumber: "P01A224022100379"