//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.26 at 04:05:13 PM IST 
//


package com.ina.parameters.packages.xml.v6.catm116;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AttributeType1Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="AttributeType1Code"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="CNAT"/&gt;
 *     &lt;enumeration value="LATT"/&gt;
 *     &lt;enumeration value="OATT"/&gt;
 *     &lt;enumeration value="OUAT"/&gt;
 *     &lt;enumeration value="CATT"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "AttributeType1Code")
@XmlEnum
public enum AttributeType1Code {

    CNAT,
    LATT,
    OATT,
    OUAT,
    CATT;

    public String value() {
        return name();
    }

    public static AttributeType1Code fromValue(String v) {
        return valueOf(v);
    }

}
