//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.26 at 04:05:13 PM IST 
//


package com.ina.parameters.packages.xml.v6.catm116;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for POIComponentStatus1Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="POIComponentStatus1Code"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="WAIT"/&gt;
 *     &lt;enumeration value="OUTD"/&gt;
 *     &lt;enumeration value="OPER"/&gt;
 *     &lt;enumeration value="DACT"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "POIComponentStatus1Code")
@XmlEnum
public enum POIComponentStatus1Code {

    WAIT,
    OUTD,
    OPER,
    DACT;

    public String value() {
        return name();
    }

    public static POIComponentStatus1Code fromValue(String v) {
        return valueOf(v);
    }

}
