//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.13 at 01:59:09 PM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "urn:iso:std:iso:20022:tech:xsd:catm.001.001.06", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ina.nexotms.packages.xml.v6.catm116;
