//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.26 at 04:05:15 PM IST 
//


package com.ina.parameters.packages.xml.v8.catm515;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Algorithm8Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="Algorithm8Code"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="MGF1"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "Algorithm8Code")
@XmlEnum
public enum Algorithm8Code {

    @XmlEnumValue("MGF1")
    MGF_1("MGF1");
    private final String value;

    Algorithm8Code(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Algorithm8Code fromValue(String v) {
        for (Algorithm8Code c: Algorithm8Code.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
