//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.26 at 04:05:15 PM IST 
//


package com.ina.parameters.packages.xml.v8.catm515;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MessageItemCondition1Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="MessageItemCondition1Code"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="MNDT"/&gt;
 *     &lt;enumeration value="CFVL"/&gt;
 *     &lt;enumeration value="DFLT"/&gt;
 *     &lt;enumeration value="ALWV"/&gt;
 *     &lt;enumeration value="IFAV"/&gt;
 *     &lt;enumeration value="COPY"/&gt;
 *     &lt;enumeration value="UNSP"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "MessageItemCondition1Code")
@XmlEnum
public enum MessageItemCondition1Code {

    MNDT,
    CFVL,
    DFLT,
    ALWV,
    IFAV,
    COPY,
    UNSP;

    public String value() {
        return name();
    }

    public static MessageItemCondition1Code fromValue(String v) {
        return valueOf(v);
    }

}
