//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.26 at 04:05:14 PM IST 
//


package com.ina.parameters.packages.xml.v6.catm513;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MaintenanceIdentificationAssociation1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MaintenanceIdentificationAssociation1"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MstrTMId" type="{urn:iso:std:iso:20022:tech:xsd:catm.005.001.03}Max35Text"/&gt;
 *         &lt;element name="TMId" type="{urn:iso:std:iso:20022:tech:xsd:catm.005.001.03}Max35Text"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MaintenanceIdentificationAssociation1", propOrder = {
    "mstrTMId",
    "tmId"
})
public class MaintenanceIdentificationAssociation1 {

    @XmlElement(name = "MstrTMId", required = true)
    protected String mstrTMId;
    @XmlElement(name = "TMId", required = true)
    protected String tmId;

    /**
     * Gets the value of the mstrTMId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMstrTMId() {
        return mstrTMId;
    }

    /**
     * Sets the value of the mstrTMId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMstrTMId(String value) {
        this.mstrTMId = value;
    }

    /**
     * Gets the value of the tmId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTMId() {
        return tmId;
    }

    /**
     * Sets the value of the tmId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTMId(String value) {
        this.tmId = value;
    }

}
