//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.26 at 04:05:14 PM IST 
//


package com.ina.parameters.packages.xml.v6.catm711;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PointOfInteraction6 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PointOfInteraction6"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ManfctrIdr" type="{urn:iso:std:iso:20022:tech:xsd:catm.007.001.01}Max35Text"/&gt;
 *         &lt;element name="Mdl" type="{urn:iso:std:iso:20022:tech:xsd:catm.007.001.01}Max35Text"/&gt;
 *         &lt;element name="SrlNb" type="{urn:iso:std:iso:20022:tech:xsd:catm.007.001.01}Max35Text"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PointOfInteraction6", propOrder = {
    "manfctrIdr",
    "mdl",
    "srlNb"
})
public class PointOfInteraction6 {

    @XmlElement(name = "ManfctrIdr", required = true)
    protected String manfctrIdr;
    @XmlElement(name = "Mdl", required = true)
    protected String mdl;
    @XmlElement(name = "SrlNb", required = true)
    protected String srlNb;

    /**
     * Gets the value of the manfctrIdr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManfctrIdr() {
        return manfctrIdr;
    }

    /**
     * Sets the value of the manfctrIdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManfctrIdr(String value) {
        this.manfctrIdr = value;
    }

    /**
     * Gets the value of the mdl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMdl() {
        return mdl;
    }

    /**
     * Sets the value of the mdl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMdl(String value) {
        this.mdl = value;
    }

    /**
     * Gets the value of the srlNb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrlNb() {
        return srlNb;
    }

    /**
     * Sets the value of the srlNb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrlNb(String value) {
        this.srlNb = value;
    }

}
