//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.13 at 01:59:10 PM IST 
//


package com.ina.nexotms.packages.xml.v6.catm513;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TerminalManagementAdditionalProcess1Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="TerminalManagementAdditionalProcess1Code"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="MANC"/&gt;
 *     &lt;enumeration value="RCNC"/&gt;
 *     &lt;enumeration value="RSRT"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TerminalManagementAdditionalProcess1Code")
@XmlEnum
public enum TerminalManagementAdditionalProcess1Code {

    MANC,
    RCNC,
    RSRT;

    public String value() {
        return name();
    }

    public static TerminalManagementAdditionalProcess1Code fromValue(String v) {
        return valueOf(v);
    }

}
