//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.13 at 01:59:12 PM IST 
//


package com.ina.nexotms.packages.xml.v8.catm515;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NetworkParameters6 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NetworkParameters6"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Tp" type="{urn:iso:std:iso:20022:tech:xsd:catm.005.001.05}NetworkType2Code"/&gt;
 *         &lt;element name="Accs" type="{urn:iso:std:iso:20022:tech:xsd:catm.005.001.05}NetworkParameters5"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NetworkParameters6", propOrder = {
    "tp",
    "accs"
})
public class NetworkParameters6 {

    @XmlElement(name = "Tp", required = true)
    @XmlSchemaType(name = "string")
    protected NetworkType2Code tp;
    @XmlElement(name = "Accs", required = true)
    protected NetworkParameters5 accs;

    /**
     * Gets the value of the tp property.
     * 
     * @return
     *     possible object is
     *     {@link NetworkType2Code }
     *     
     */
    public NetworkType2Code getTp() {
        return tp;
    }

    /**
     * Sets the value of the tp property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetworkType2Code }
     *     
     */
    public void setTp(NetworkType2Code value) {
        this.tp = value;
    }

    /**
     * Gets the value of the accs property.
     * 
     * @return
     *     possible object is
     *     {@link NetworkParameters5 }
     *     
     */
    public NetworkParameters5 getAccs() {
        return accs;
    }

    /**
     * Sets the value of the accs property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetworkParameters5 }
     *     
     */
    public void setAccs(NetworkParameters5 value) {
        this.accs = value;
    }

}
