//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.13 at 01:59:10 PM IST 
//


package com.ina.nexotms.packages.xml.v6.catm316;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ina.nexotms.packages.xml.v6.catm316 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Document_QNAME = new QName("urn:iso:std:iso:20022:tech:xsd:catm.003.001.06", "Document");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ina.nexotms.packages.xml.v6.catm316
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link AcceptorConfiguration6 }
     * 
     */
    public AcceptorConfiguration6 createAcceptorConfiguration6() {
        return new AcceptorConfiguration6();
    }

    /**
     * Create an instance of {@link AcceptorConfigurationContent6 }
     * 
     */
    public AcceptorConfigurationContent6 createAcceptorConfigurationContent6() {
        return new AcceptorConfigurationContent6();
    }

    /**
     * Create an instance of {@link AcceptorConfigurationUpdateV06 }
     * 
     */
    public AcceptorConfigurationUpdateV06 createAcceptorConfigurationUpdateV06() {
        return new AcceptorConfigurationUpdateV06();
    }

    /**
     * Create an instance of {@link AcquirerHostConfiguration4 }
     * 
     */
    public AcquirerHostConfiguration4 createAcquirerHostConfiguration4() {
        return new AcquirerHostConfiguration4();
    }

    /**
     * Create an instance of {@link AcquirerProtocolParameters10 }
     * 
     */
    public AcquirerProtocolParameters10 createAcquirerProtocolParameters10() {
        return new AcquirerProtocolParameters10();
    }

    /**
     * Create an instance of {@link AcquirerProtocolParameters8 }
     * 
     */
    public AcquirerProtocolParameters8 createAcquirerProtocolParameters8() {
        return new AcquirerProtocolParameters8();
    }

    /**
     * Create an instance of {@link AlgorithmIdentification11 }
     * 
     */
    public AlgorithmIdentification11 createAlgorithmIdentification11() {
        return new AlgorithmIdentification11();
    }

    /**
     * Create an instance of {@link AlgorithmIdentification12 }
     * 
     */
    public AlgorithmIdentification12 createAlgorithmIdentification12() {
        return new AlgorithmIdentification12();
    }

    /**
     * Create an instance of {@link AlgorithmIdentification13 }
     * 
     */
    public AlgorithmIdentification13 createAlgorithmIdentification13() {
        return new AlgorithmIdentification13();
    }

    /**
     * Create an instance of {@link AlgorithmIdentification14 }
     * 
     */
    public AlgorithmIdentification14 createAlgorithmIdentification14() {
        return new AlgorithmIdentification14();
    }

    /**
     * Create an instance of {@link AlgorithmIdentification15 }
     * 
     */
    public AlgorithmIdentification15 createAlgorithmIdentification15() {
        return new AlgorithmIdentification15();
    }

    /**
     * Create an instance of {@link AlgorithmIdentification16 }
     * 
     */
    public AlgorithmIdentification16 createAlgorithmIdentification16() {
        return new AlgorithmIdentification16();
    }

    /**
     * Create an instance of {@link AlgorithmIdentification17 }
     * 
     */
    public AlgorithmIdentification17 createAlgorithmIdentification17() {
        return new AlgorithmIdentification17();
    }

    /**
     * Create an instance of {@link ApplicationParameters6 }
     * 
     */
    public ApplicationParameters6 createApplicationParameters6() {
        return new ApplicationParameters6();
    }

    /**
     * Create an instance of {@link AuthenticatedData4 }
     * 
     */
    public AuthenticatedData4 createAuthenticatedData4() {
        return new AuthenticatedData4();
    }

    /**
     * Create an instance of {@link CertificateIssuer1 }
     * 
     */
    public CertificateIssuer1 createCertificateIssuer1() {
        return new CertificateIssuer1();
    }

    /**
     * Create an instance of {@link ClockSynchronisation1 }
     * 
     */
    public ClockSynchronisation1 createClockSynchronisation1() {
        return new ClockSynchronisation1();
    }

    /**
     * Create an instance of {@link ContentInformationType10 }
     * 
     */
    public ContentInformationType10 createContentInformationType10() {
        return new ContentInformationType10();
    }

    /**
     * Create an instance of {@link ContentInformationType12 }
     * 
     */
    public ContentInformationType12 createContentInformationType12() {
        return new ContentInformationType12();
    }

    /**
     * Create an instance of {@link CryptographicKey5 }
     * 
     */
    public CryptographicKey5 createCryptographicKey5() {
        return new CryptographicKey5();
    }

    /**
     * Create an instance of {@link DataSetIdentification6 }
     * 
     */
    public DataSetIdentification6 createDataSetIdentification6() {
        return new DataSetIdentification6();
    }

    /**
     * Create an instance of {@link DigestedData4 }
     * 
     */
    public DigestedData4 createDigestedData4() {
        return new DigestedData4();
    }

    /**
     * Create an instance of {@link EncapsulatedContent3 }
     * 
     */
    public EncapsulatedContent3 createEncapsulatedContent3() {
        return new EncapsulatedContent3();
    }

    /**
     * Create an instance of {@link EncryptedContent3 }
     * 
     */
    public EncryptedContent3 createEncryptedContent3() {
        return new EncryptedContent3();
    }

    /**
     * Create an instance of {@link EnvelopedData4 }
     * 
     */
    public EnvelopedData4 createEnvelopedData4() {
        return new EnvelopedData4();
    }

    /**
     * Create an instance of {@link ExchangeConfiguration6 }
     * 
     */
    public ExchangeConfiguration6 createExchangeConfiguration6() {
        return new ExchangeConfiguration6();
    }

    /**
     * Create an instance of {@link ExchangeConfiguration7 }
     * 
     */
    public ExchangeConfiguration7 createExchangeConfiguration7() {
        return new ExchangeConfiguration7();
    }

    /**
     * Create an instance of {@link GenericIdentification53 }
     * 
     */
    public GenericIdentification53 createGenericIdentification53() {
        return new GenericIdentification53();
    }

    /**
     * Create an instance of {@link GenericIdentification71 }
     * 
     */
    public GenericIdentification71 createGenericIdentification71() {
        return new GenericIdentification71();
    }

    /**
     * Create an instance of {@link GenericIdentification92 }
     * 
     */
    public GenericIdentification92 createGenericIdentification92() {
        return new GenericIdentification92();
    }

    /**
     * Create an instance of {@link Header27 }
     * 
     */
    public Header27 createHeader27() {
        return new Header27();
    }

    /**
     * Create an instance of {@link HostCommunicationParameter4 }
     * 
     */
    public HostCommunicationParameter4 createHostCommunicationParameter4() {
        return new HostCommunicationParameter4();
    }

    /**
     * Create an instance of {@link IssuerAndSerialNumber1 }
     * 
     */
    public IssuerAndSerialNumber1 createIssuerAndSerialNumber1() {
        return new IssuerAndSerialNumber1();
    }

    /**
     * Create an instance of {@link KEK4 }
     * 
     */
    public KEK4 createKEK4() {
        return new KEK4();
    }

    /**
     * Create an instance of {@link KEKIdentifier2 }
     * 
     */
    public KEKIdentifier2 createKEKIdentifier2() {
        return new KEKIdentifier2();
    }

    /**
     * Create an instance of {@link KEKIdentifier5 }
     * 
     */
    public KEKIdentifier5 createKEKIdentifier5() {
        return new KEKIdentifier5();
    }

    /**
     * Create an instance of {@link KeyTransport4 }
     * 
     */
    public KeyTransport4 createKeyTransport4() {
        return new KeyTransport4();
    }

    /**
     * Create an instance of {@link LocalDateTime1 }
     * 
     */
    public LocalDateTime1 createLocalDateTime1() {
        return new LocalDateTime1();
    }

    /**
     * Create an instance of {@link MerchantConfigurationParameters3 }
     * 
     */
    public MerchantConfigurationParameters3 createMerchantConfigurationParameters3() {
        return new MerchantConfigurationParameters3();
    }

    /**
     * Create an instance of {@link MessageItemCondition1 }
     * 
     */
    public MessageItemCondition1 createMessageItemCondition1() {
        return new MessageItemCondition1();
    }

    /**
     * Create an instance of {@link NetworkParameters2 }
     * 
     */
    public NetworkParameters2 createNetworkParameters2() {
        return new NetworkParameters2();
    }

    /**
     * Create an instance of {@link NetworkParameters3 }
     * 
     */
    public NetworkParameters3 createNetworkParameters3() {
        return new NetworkParameters3();
    }

    /**
     * Create an instance of {@link NetworkParameters4 }
     * 
     */
    public NetworkParameters4 createNetworkParameters4() {
        return new NetworkParameters4();
    }

    /**
     * Create an instance of {@link NetworkParameters5 }
     * 
     */
    public NetworkParameters5 createNetworkParameters5() {
        return new NetworkParameters5();
    }

    /**
     * Create an instance of {@link NetworkParameters6 }
     * 
     */
    public NetworkParameters6 createNetworkParameters6() {
        return new NetworkParameters6();
    }

    /**
     * Create an instance of {@link Parameter4 }
     * 
     */
    public Parameter4 createParameter4() {
        return new Parameter4();
    }

    /**
     * Create an instance of {@link Parameter5 }
     * 
     */
    public Parameter5 createParameter5() {
        return new Parameter5();
    }

    /**
     * Create an instance of {@link Parameter6 }
     * 
     */
    public Parameter6 createParameter6() {
        return new Parameter6();
    }

    /**
     * Create an instance of {@link Parameter7 }
     * 
     */
    public Parameter7 createParameter7() {
        return new Parameter7();
    }

    /**
     * Create an instance of {@link Parameter8 }
     * 
     */
    public Parameter8 createParameter8() {
        return new Parameter8();
    }

    /**
     * Create an instance of {@link PaymentTerminalParameters4 }
     * 
     */
    public PaymentTerminalParameters4 createPaymentTerminalParameters4() {
        return new PaymentTerminalParameters4();
    }

    /**
     * Create an instance of {@link ProcessRetry2 }
     * 
     */
    public ProcessRetry2 createProcessRetry2() {
        return new ProcessRetry2();
    }

    /**
     * Create an instance of {@link ProcessTiming4 }
     * 
     */
    public ProcessTiming4 createProcessTiming4() {
        return new ProcessTiming4();
    }

    /**
     * Create an instance of {@link Recipient4Choice }
     * 
     */
    public Recipient4Choice createRecipient4Choice() {
        return new Recipient4Choice();
    }

    /**
     * Create an instance of {@link Recipient5Choice }
     * 
     */
    public Recipient5Choice createRecipient5Choice() {
        return new Recipient5Choice();
    }

    /**
     * Create an instance of {@link RelativeDistinguishedName1 }
     * 
     */
    public RelativeDistinguishedName1 createRelativeDistinguishedName1() {
        return new RelativeDistinguishedName1();
    }

    /**
     * Create an instance of {@link SecurityParameters6 }
     * 
     */
    public SecurityParameters6 createSecurityParameters6() {
        return new SecurityParameters6();
    }

    /**
     * Create an instance of {@link SignedData4 }
     * 
     */
    public SignedData4 createSignedData4() {
        return new SignedData4();
    }

    /**
     * Create an instance of {@link Signer3 }
     * 
     */
    public Signer3 createSigner3() {
        return new Signer3();
    }

    /**
     * Create an instance of {@link TMSProtocolParameters2 }
     * 
     */
    public TMSProtocolParameters2 createTMSProtocolParameters2() {
        return new TMSProtocolParameters2();
    }

    /**
     * Create an instance of {@link TerminalManagementDataSet20 }
     * 
     */
    public TerminalManagementDataSet20 createTerminalManagementDataSet20() {
        return new TerminalManagementDataSet20();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Document }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Document }{@code >}
     */
    @XmlElementDecl(namespace = "urn:iso:std:iso:20022:tech:xsd:catm.003.001.06", name = "Document")
    public JAXBElement<Document> createDocument(Document value) {
        return new JAXBElement<Document>(_Document_QNAME, Document.class, null, value);
    }

}
