//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.13 at 01:59:11 PM IST 
//


package com.ina.nexotms.packages.xml.v8.catm118;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DataSetCategory12Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="DataSetCategory12Code"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="AQPR"/&gt;
 *     &lt;enumeration value="APPR"/&gt;
 *     &lt;enumeration value="TXCP"/&gt;
 *     &lt;enumeration value="AKCP"/&gt;
 *     &lt;enumeration value="DLGT"/&gt;
 *     &lt;enumeration value="MGTP"/&gt;
 *     &lt;enumeration value="MRPR"/&gt;
 *     &lt;enumeration value="SCPR"/&gt;
 *     &lt;enumeration value="SWPK"/&gt;
 *     &lt;enumeration value="STRP"/&gt;
 *     &lt;enumeration value="TRPR"/&gt;
 *     &lt;enumeration value="VDPR"/&gt;
 *     &lt;enumeration value="PARA"/&gt;
 *     &lt;enumeration value="TMSP"/&gt;
 *     &lt;enumeration value="CRTF"/&gt;
 *     &lt;enumeration value="LOGF"/&gt;
 *     &lt;enumeration value="CMRQ"/&gt;
 *     &lt;enumeration value="StatusReport"/&gt;
 *     &lt;enumeration value="Register"/&gt;
 *     &lt;enumeration value="Parameters"/&gt;
 *     &lt;enumeration value="SecurityParameters"/&gt;
 *     &lt;enumeration value="ManagementPlan"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "DataSetCategory12Code")
@XmlEnum
public enum DataSetCategory12Code {

    AQPR("AQPR"),
    APPR("APPR"),
    TXCP("TXCP"),
    AKCP("AKCP"),
    DLGT("DLGT"),
    MGTP("MGTP"),
    MRPR("MRPR"),
    SCPR("SCPR"),
    SWPK("SWPK"),
    STRP("STRP"),
    TRPR("TRPR"),
    VDPR("VDPR"),
    PARA("PARA"),
    TMSP("TMSP"),
    CRTF("CRTF"),
    LOGF("LOGF"),
    CMRQ("CMRQ"),
    @XmlEnumValue("StatusReport")
    STATUS_REPORT("StatusReport"),
    @XmlEnumValue("Register")
    REGISTER("Register"),
    @XmlEnumValue("Parameters")
    PARAMETERS("Parameters"),
    @XmlEnumValue("SecurityParameters")
    SECURITY_PARAMETERS("SecurityParameters"),
    @XmlEnumValue("ManagementPlan")
    MANAGEMENT_PLAN("ManagementPlan");
    private final String value;

    DataSetCategory12Code(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DataSetCategory12Code fromValue(String v) {
        for (DataSetCategory12Code c: DataSetCategory12Code.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
