//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.13 at 01:59:11 PM IST 
//


package com.ina.nexotms.packages.xml.v8.catm118;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TerminalManagementDataSet25 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TerminalManagementDataSet25"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Id" type="{urn:iso:std:iso:20022:tech:xsd:catm.001.001.08}DataSetIdentification7"/&gt;
 *         &lt;element name="POIChllng" type="{urn:iso:std:iso:20022:tech:xsd:catm.001.001.08}Max140Text" minOccurs="0"/&gt;
 *         &lt;element name="TMChllng" type="{urn:iso:std:iso:20022:tech:xsd:catm.001.001.08}Max140Text" minOccurs="0"/&gt;
 *         &lt;element name="SsnKey" type="{urn:iso:std:iso:20022:tech:xsd:catm.001.001.08}CryptographicKey13" minOccurs="0"/&gt;
 *         &lt;element name="DlgtnProof" type="{urn:iso:std:iso:20022:tech:xsd:catm.001.001.08}Max5000Binary" minOccurs="0"/&gt;
 *         &lt;element name="PrtctdDlgtnProof" type="{urn:iso:std:iso:20022:tech:xsd:catm.001.001.08}ContentInformationType19" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TerminalManagementDataSet25", propOrder = {
    "id",
    "poiChllng",
    "tmChllng",
    "ssnKey",
    "dlgtnProof",
    "prtctdDlgtnProof"
})
public class TerminalManagementDataSet25 {

    @XmlElement(name = "Id", required = true)
    protected DataSetIdentification7 id;
    @XmlElement(name = "POIChllng")
    protected String poiChllng;
    @XmlElement(name = "TMChllng")
    protected String tmChllng;
    @XmlElement(name = "SsnKey")
    protected CryptographicKey13 ssnKey;
    @XmlElement(name = "DlgtnProof")
    protected byte[] dlgtnProof;
    @XmlElement(name = "PrtctdDlgtnProof")
    protected ContentInformationType19 prtctdDlgtnProof;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link DataSetIdentification7 }
     *     
     */
    public DataSetIdentification7 getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSetIdentification7 }
     *     
     */
    public void setId(DataSetIdentification7 value) {
        this.id = value;
    }

    /**
     * Gets the value of the poiChllng property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOIChllng() {
        return poiChllng;
    }

    /**
     * Sets the value of the poiChllng property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOIChllng(String value) {
        this.poiChllng = value;
    }

    /**
     * Gets the value of the tmChllng property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTMChllng() {
        return tmChllng;
    }

    /**
     * Sets the value of the tmChllng property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTMChllng(String value) {
        this.tmChllng = value;
    }

    /**
     * Gets the value of the ssnKey property.
     * 
     * @return
     *     possible object is
     *     {@link CryptographicKey13 }
     *     
     */
    public CryptographicKey13 getSsnKey() {
        return ssnKey;
    }

    /**
     * Sets the value of the ssnKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link CryptographicKey13 }
     *     
     */
    public void setSsnKey(CryptographicKey13 value) {
        this.ssnKey = value;
    }

    /**
     * Gets the value of the dlgtnProof property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getDlgtnProof() {
        return dlgtnProof;
    }

    /**
     * Sets the value of the dlgtnProof property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setDlgtnProof(byte[] value) {
        this.dlgtnProof = value;
    }

    /**
     * Gets the value of the prtctdDlgtnProof property.
     * 
     * @return
     *     possible object is
     *     {@link ContentInformationType19 }
     *     
     */
    public ContentInformationType19 getPrtctdDlgtnProof() {
        return prtctdDlgtnProof;
    }

    /**
     * Sets the value of the prtctdDlgtnProof property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentInformationType19 }
     *     
     */
    public void setPrtctdDlgtnProof(ContentInformationType19 value) {
        this.prtctdDlgtnProof = value;
    }

}
