//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.13 at 01:59:13 PM IST 
//


package com.ina.nexotms.packages.xml.v8.catm414;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RejectReason2Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="RejectReason2Code"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="UNPR"/&gt;
 *     &lt;enumeration value="IMSG"/&gt;
 *     &lt;enumeration value="PARS"/&gt;
 *     &lt;enumeration value="SECU"/&gt;
 *     &lt;enumeration value="INTP"/&gt;
 *     &lt;enumeration value="RCPP"/&gt;
 *     &lt;enumeration value="VERS"/&gt;
 *     &lt;enumeration value="MSGT"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "RejectReason2Code")
@XmlEnum
public enum RejectReason2Code {

    UNPR,
    IMSG,
    PARS,
    SECU,
    INTP,
    RCPP,
    VERS,
    MSGT;

    public String value() {
        return name();
    }

    public static RejectReason2Code fromValue(String v) {
        return valueOf(v);
    }

}
